### ISSUE TITLE
Topology does not show running nodes?

### ISSUE THREAD

**Issue by russellday** [sumeet70/aiex#5]
Wondering if you have any troubleshooting suggestions? The only modification I made is to config.json to use port 80. I started ignite using ignite.sh examples/config/example-cache.xml. Any suggestions would be appreciated. Running a curl on http://localhost:8080/ignite?cmd=version returns the correct Ignite version so it appears the rest api is running.

2016-08-03T18:26:26.682Z - info: Configuration loaded successfully from /home/ec2-user/aiex/config.json rootPath=/api, port=80, zmqSocketAddress=tcp://127.0.0.1:5555
2016-08-03T18:26:27.209Z - info: Web Server Ready on port: 80
2016-08-03T18:26:51.457Z - info: 
2016-08-03T18:26:51.501Z - info:  Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:126:16)
2016-08-03T18:27:04.512Z - info:  key=abc, val=123
2016-08-03T18:27:04.515Z - info:  Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete](dns.js:126:16)

**Comment by russellday** [comment]
I found the issue. I believe there is a bug in the logical Or statement below (..modules/ignite/rest-service.js):

var rootUrl = "http://" + process.env.IGNITE_REST + "/ignite?cmd=" || "http://localhost:8080/ignite?cmd=";

if IGNITE_REST is undefined it evaluates to "http://undefined/ignite?cmd=".

I modified as shown below.

var r = process.env.IGNITE_REST;
var rootUrl = r !== undefined ? "http://" + process.env.IGNITE_REST + "/ignite?cmd=" : "http://localhost:8080/ignite?cmd=";

**Comment by artbasov** [comment]
@russellday This solves the issue for me as well. Mind issue PR ? Though project seems to stall.
